import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const geistSans = {
  variable: "--font-geist-sans",
};

export const metadata = {
  title: "Next.js with Windsurf - Product",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistSans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
